[package]
name = "async-in-wasm"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.35"
wasm-bindgen = "0.2.58"
wasm-bindgen-futures = "0.4.8"
